CREATE TABLE account (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, mdp VARCHAR(2
55) NOT NULL, level INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicod
e_ci ENGINE = InnoDB;
     CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) NOT NULL, description LON
GTEXT NOT NULL, date_publication DATE NOT NULL, time_publication TIME NOT NULL, PRIMARY KEY(id)) DEFAUL
T CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, roles LONGTEXT
NOT NULL COMMENT '(DC2Type:json)', password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (
username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
